In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_excel(r"D:\JAIMIN\Data Science\Machine Learning\real+estate+valuation+data+set\Real estate valuation data set.xlsx")

In [3]:
df.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.describe()

No  X1 transaction date  X2 house age  \
count  414.000000           414.000000    414.000000   
mean   207.500000          2013.148953     17.712560   
std    119.655756             0.281995     11.392485   
min      1.000000          2012.666667      0.000000   
25%    104.250000          2012.916667      9.025000   
50%    207.500000          2013.166667     16.100000   
75%    310.750000          2013.416667     28.150000   
max    414.000000          2013.583333     43.800000   

       X3 distance to the nearest MRT station  \
count                              414.000000   
mean                              1083.885689   
std                               1262.109595   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1454.279000   
max                               6488.021000   

       X4 number of convenience stores  X5 latitude  X6 longitude  \
count                       414.000000   414.000000    414.000000   
mean                          4.094203    24.969030    121.533361   
std                           2.945562     0.012410      0.015347   
min                           0.000000    24.932070    121.473530   
25%                           1.000000    24.963000    121.528085   
50%                           4.000000    24.971100    121.538630   
75%                           6.000000    24.977455    121.543305   
max                          10.000000    25.014590    121.566270   

       Y house price of unit area  
count                  414.000000  
mean                    37.980193  
std                     13.606488  
min                      7.600000  
25%                     27.700000  
50%                     38.450000  
75%                     46.600000  
max                    117.500000

In [6]:
df

No  X1 transaction date  X2 house age  \
0      1          2012.916667          32.0   
1      2          2012.916667          19.5   
2      3          2013.583333          13.3   
3      4          2013.500000          13.3   
4      5          2012.833333           5.0   
..   ...                  ...           ...   
409  410          2013.000000          13.7   
410  411          2012.666667           5.6   
411  412          2013.250000          18.8   
412  413          2013.000000           8.1   
413  414          2013.500000           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [7]:
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [8]:
y = df[['Y house price of unit area']]
y.head()

Y house price of unit area
0                        37.9
1                        42.2
2                        47.3
3                        54.8
4                        43.1

In [9]:
x =df.drop(columns =["Y house price of unit area"])
x

No  X1 transaction date  X2 house age  \
0      1          2012.916667          32.0   
1      2          2012.916667          19.5   
2      3          2013.583333          13.3   
3      4          2013.500000          13.3   
4      5          2012.833333           5.0   
..   ...                  ...           ...   
409  410          2013.000000          13.7   
410  411          2012.666667           5.6   
411  412          2013.250000          18.8   
412  413          2013.000000           8.1   
413  414          2013.500000           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  
0       24.98298     121.54024  
1       24.98034     121.53951  
2       24.98746     121.54391  
3       24.98746     121.54391  
4       24.97937     121.54245  
..           ...           ...  
409     24.94155     121.50381  
410     24.97433     121.54310  
411     24.97923     121.53986  
412     24.96674     121.54067  
413     24.97433     121.54310  

[414 rows x 7 columns]

In [10]:
scaler = StandardScaler()

In [11]:
arr=scaler.fit_transform(x)

In [12]:
arr

array([[-1.72787215, -0.82472165,  1.25562833, ...,  2.00740743,
         1.12542986,  0.44876222],
       [-1.71950473, -0.82472165,  0.15708622, ...,  1.66750286,
         0.91244418,  0.40113894],
       [-1.71113731,  1.54224386, -0.38779067, ...,  0.30788458,
         1.48686011,  0.68818339],
       ...,
       [ 1.71113731,  0.35876111,  0.09556786, ...,  0.98769372,
         0.82289338,  0.42397202],
       [ 1.71950473, -0.52885105, -0.84478419, ...,  0.30788458,
        -0.18475479,  0.4768143 ],
       [ 1.72787215,  1.24637326, -0.98539758, ...,  1.66750286,
         0.42757905,  0.63534112]])

In [13]:
df1=pd.DataFrame(arr)

In [14]:
df1.head(10)

0         1         2         3         4         5         6
0 -1.727872 -0.824722  1.255628 -0.792495  2.007407  1.125430  0.448762
1 -1.719505 -0.824722  0.157086 -0.616612  1.667503  0.912444  0.401139
2 -1.711137  1.542244 -0.387791 -0.414015  0.307885  1.486860  0.688183
3 -1.702770  1.246373 -0.387791 -0.414015  0.307885  1.486860  0.688183
4 -1.694402 -1.120593 -1.117223 -0.549997  0.307885  0.834188  0.592937
5 -1.686035 -1.712334 -0.932668  0.865586 -0.371925 -0.482451 -1.358313
6 -1.677668 -1.712334  1.475337 -0.365237  0.987694  0.830961  0.199555
7 -1.669300  0.950503  0.227393 -0.631678  0.647789  0.918898  0.581846
8 -1.660933  1.246373  1.229263  3.512777 -1.051734 -1.458635 -3.182350
9 -1.652565  0.950503  0.016473  0.554738 -0.371925 -0.138769 -1.206962

In [15]:
df1.describe()

0             1             2             3             4  \
count  4.140000e+02  4.140000e+02  4.140000e+02  4.140000e+02  4.140000e+02   
mean  -6.865147e-17 -5.030522e-13 -9.225042e-17 -1.265762e-16 -7.508755e-18   
std    1.001210e+00  1.001210e+00  1.001210e+00  1.001210e+00  1.001210e+00   
min   -1.727872e+00 -1.712334e+00 -1.556639e+00 -8.412787e-01 -1.391638e+00   
25%   -8.639361e-01 -8.247217e-01 -7.634921e-01 -6.303115e-01 -1.051734e+00   
50%    0.000000e+00  6.289051e-02 -1.417172e-01 -4.693493e-01 -3.202000e-02   
75%    8.639361e-01  9.505027e-01  9.172774e-01  2.938267e-01  6.477891e-01   
max    1.727872e+00  1.542244e+00  2.292652e+00  4.287008e+00  2.007407e+00   

                  5             6  
count  4.140000e+02  4.140000e+02  
mean   1.343166e-13 -1.614537e-12  
std    1.001210e+00  1.001210e+00  
min   -2.981805e+00 -3.903223e+00  
25%   -4.864845e-01 -3.441981e-01  
50%    1.669943e-01  3.437301e-01  
75%    6.796928e-01  6.487148e-01  
max    3.675611e+00  2.146891e+00

In [16]:
df.shape

(414, 8)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(
    arr, y, test_size=0.30, random_state=42)

In [19]:
x_train

array([[-1.66930021,  0.95050266,  0.22739291, ...,  0.64778915,
         0.91889829,  0.58184647],
       [-0.10459275,  1.24637326, -0.22081227, ..., -1.39163828,
        -2.85595023, -1.42094092],
       [-1.56889118, -1.71233381, -1.42481443, ...,  0.98769372,
        -0.10569192,  0.49964738],
       ...,
       [ 0.53133115,  0.65463171, -0.6074991 , ..., -1.05173371,
         0.44936167, -0.1892593 ],
       [ 1.18398988, -1.12059261, -1.15237598, ...,  0.64778915,
         0.55020717,  0.76973011],
       [-0.87439535, -0.23298045, -1.45996777, ...,  0.64778915,
        -0.26785148,  0.49116652]])

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [21]:
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
df.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [23]:
lr.predict([[1,2012.91667,32.0,84.87882,10,24.98298,121.54024]])

array([[2717.03282286]])

In [24]:
import pickle
pickle.dump(lr,open('Real_Estate_Valuation_model.pickle', 'wb'))

In [25]:
%ls # linux command

 Volume in drive C is OS
 Volume Serial Number is E077-265C

 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science



File Not Found


In [26]:
model=pickle.load((open('Real_Estate_Valuation_model.pickle','rb')))

In [27]:
model

LinearRegression()

In [28]:
test1=scaler.transform([[1,2012.91667,32.0,84.87882,10,24.98298,121.54024]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [29]:
model.predict(test1)

array([[48.94924882]])

In [30]:
test2=scaler.transform([[2,2012.916667,19.5,306.59470,9,24.98034,121.53951]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [31]:
df.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [32]:
model.predict(test2)

array([[49.12893792]])

In [33]:
lr.score(x_test,y_test)

0.553260668069211

In [34]:
lr.score(x_train,y_train)

0.5889110826305727

In [35]:
base_preds=lr.predict(x_test)
base_preds

array([[46.63320335],
       [40.24079473],
       [43.27627797],
       [39.42129907],
       [26.4142282 ],
       [46.76223257],
       [44.37062376],
       [47.01653995],
       [24.73031228],
       [55.21056178],
       [35.24540757],
       [36.78701351],
       [36.45707229],
       [24.60261704],
       [36.61434464],
       [33.53726384],
       [45.03474494],
       [44.58273068],
       [28.94295624],
       [44.76254263],
       [ 0.46646852],
       [36.54747017],
       [47.03710103],
       [46.03858927],
       [ 9.80711905],
       [38.86502969],
       [11.6878835 ],
       [43.58228147],
       [36.53185332],
       [38.39678541],
       [14.01896572],
       [40.5278996 ],
       [36.18708142],
       [27.92883729],
       [47.68163384],
       [31.72416406],
       [50.11795883],
       [11.90941479],
       [49.73220179],
       [39.970386  ],
       [40.31131297],
       [40.32543301],
       [48.94922947],
       [37.02785481],
       [39.31142274],
       [47

In [36]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [37]:
mean_absolute_error(y_test,base_preds)

6.266394112748088

In [38]:
np.sqrt(mean_squared_error(y_test,base_preds))

8.643265394245798

In [39]:
y_test.mean()

Y house price of unit area    36.9128
dtype: float64